sudo: required
services:
  - docker

before_install:
  - docker build -t mallachari/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mallachari/react-test npm run test -- --coverage

after_success:
  - docker build -t mallachari/multi-client ./client
  - docker build -t mallachari/multi-nginx ./nginx
  - docker build -t mallachari/multi-server ./server
  - docker build -t mallachari/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push mallachari/multi-client
  - docker push mallachari/multi-nginx
  - docker push mallachari/multi-server
  - docker push mallachari/multi-worker
